---
title: "Research"
editor: source
---

## Overview

### Ecosystem Ecology

My research in ecosystem ecology has focused on both carbon and nitrogen cycling,
primarily in northern temperate forests.  

[**Litter Decomposition in a Changing Climate**](https://ecoevorxiv.org/repository/view/9160/)

This study explored multiple impacts of climate change on leaf litter decomposition in a unique global change experiment, *Boreal Forest Warming at an Ecotone in Danger*. We found that both rainfall reduction and warming resulted in slower decomposition but rainfall reduction had a stronger effect. Growing leaf litter under warmed conditions also shifted decomposition rates in unexpected ways.   

[**Using Plant Traits to Understand Nitrogen Acquisition**](https://conservancy.umn.edu/items/4fb023ab-0e33-4330-9370-15ac49464c00)

"In many ecosystems, nitrogen (N) is the predominant nutrient limiting plant growth. Plants have therefore developed diverse strategies to compete for and partition soil N resources to ensure an adequate N supply. Differences in how plants acquire N may be important for predicting plant responses to different global changes. In particular, how species respond to climate change may depend on their N use strategy since climate change will likely alter the forms of N available to plants as well as total N availability. However, there remain key gaps in our understanding of plant N acquisition that impede our ability to project the impacts of climate change on plant communities. My research focuses on one of these gaps, the variation in plant use of different chemical forms of N, and examines how that variation can influence plant responses to climate change. Specifically, my research aims to increase our understanding of N acquisition in trees by examining whether plant traits can improve our ability to identify and explain differences in the use of different N forms."

### Biodiversity 

[**Tree Diversity and Survival**](https://onlinelibrary.wiley.com/doi/10.1111/rec.13927)

This project examined how tree species richness influenced sapling survival in a reforestation experiment, *BiodiversiTREE*, to offer insight into how to craft more successful tree plantings for future reforestation efforts.

**Tree Diversity Impacts on Soil Carbon Storage**

Reforestation efforts are often touted as having the potential to sequester carbon, but frequently focus solely on aboveground pools of carbon. This project focuses on understanding how different aspects of tree diversity influenced soil carbon storage in the early stages of a reforestation effort. 

### Conservation

**Using SSDMs to Understand Distributions of Prey Items for Endangered Species**

Species distribution models are a common tool for conservation practioners. Here we explore how stacked-SDMs for prey of threatened and endangered species can be used to help identify priority areas for conservation.

**Improving Biodiversity Monitoring Through Conservation Technology**

Successful conservation relies on assessing and monitoring the outcomes of actions taken to protect species as well as understanding the status of species populations. Conservation technology has the potential to improve our capacity to monitor biodiversity, yet it's [potential far exceeds it's implementation](https://iopscience.iop.org/article/10.1088/1748-9326/add02d). At NCEAS I am working to understand both the current scope of automated biodiversity monitoring and ways to improve our capacity to monitor with these technologies through working groups and collaborative research. 


## Publications

### Ecosystem Ecology

**[Leaf litter and fine roots have distinct effects on particulate and mineral-associated soil organic matter in a tree common garden](https://nph.onlinelibrary.wiley.com/doi/10.1111/nph.70854)**
Lang A, King RA, Pullen J, Fahey C, Parker JD, Phillips RP. *New Phytologist*. 2026.

**[Sources of variation in nutrient loads collected through street sweeping in the Minneapolis-St. Paul Metropolitan Area, Minnesota, USA](https://www.sciencedirect.com/science/article/abs/pii/S0048969723055596)**
Hobbie SE, King RA, Belo T, Kalinosky P, Baker LA, Finlay JC, et al. *Science of the Total Environment*. 2023.

### Biodiversity

**[Patronus charm: a comparison of benefactor plants and climate mediation effects on diversity](https://nsojournals.onlinelibrary.wiley.com/doi/full/10.1111/oik.10292)**
Lortie CJ, Liczner A, Ruttan A, Braun J, Sotomayor DA, Westphal M, King R, et al. *Oikos*. 2024.

**[The microclimatic effects of the native shrub *Ephedra californica* (Mormon tea) in California drylands](https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2024.1396004/full)**
Ghazian N, King R, Zuliani M, Lortie CJ. *Frontiers in Plant Science*. 2024.

**[Diversity stabilizes but does not increase sapling survival in a tree diversity experiment](https://onlinelibrary.wiley.com/doi/10.1111/rec.13927)**
King RA, Pullen J, Cook-Patton SC, Parker JD. *Restoration Ecology*. 2023.

**[Long-term monitoring of a highly invaded annual grassland community through drought, before and after an unintentional fire](https://onlinelibrary.wiley.com/doi/10.1111/jvs.12833)**
Thomson DM, Bonaparte AD, King RA, Schultz EL, Startin CR. *Journal of Vegetation Science*. 2020.

**[Between invaders and a risky place: Exotic grasses alter demographic tradeoffs of native forb germination timing](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.1987)**
Thomson DM, King RA, Schultz EL. *Ecosphere*. 2017.

### Conservation

**[Implementation of automated biodiversity monitoring lags behind its potential](https://iopscience.iop.org/article/10.1088/1748-9326/add02d)**
King RA, Halpern BS. *Environmental Research Letters*. 2025.

**[Prey Distribution Mapping to Support Conservation Planning](https://onlinelibrary.wiley.com/doi/10.1111/ddi.70048)**
King RA, Braun J, Westphal M, Lortie CJ. *Diversity and Distributions*. 2025.

**[The importance of open data describing prey item species lists for endangered species](https://besjournals.onlinelibrary.wiley.com/doi/10.1002/2688-8319.12251)**
Lortie CJ, Braun J, King R, Westphal M. *Ecological Solutions and Evidence*. 2023.

### Plant Ecology

**[Effects of heat and smoke on the germination of six Florida scrub species](https://www.sciencedirect.com/science/article/pii/S0254629916301764)**
King RA, Menges ES. *South African Journal of Botany*. 2018.
